worker_processes 1;

events {
  worker_connections 1024;
}

http {
#   include /etc/nginx/mime.types;
#   default_type application/octet-stream;

  upstream auth_service {
    server auth-service:3001;
  }

  upstream user_service {
    server user-service:3002;
  }

  upstream product_service {
    server product-service:3003;
  }

  upstream inventory_service {
    server inventory-service:3004;
  }

  upstream client_service {
    server client-service:3005;
  }

  upstream assignment_service {
    server assignment-service:3006;
  }

  upstream notification_service {
    server notification-service:3007;
  }

  upstream report_service {
    server report-service:3008;
  }

  server {
    listen 80;
    server_name localhost;

    client_max_body_size 10m;

    add_header Access-Control-Allow-Origin "http://localhost:5173" always;
    add_header Access-Control-Allow-Credentials true always;
    add_header Access-Control-Allow-Headers "Authorization,Content-Type" always;
    add_header Access-Control-Allow-Methods "GET,POST,PUT,PATCH,DELETE,OPTIONS" always;

    if ($request_method = OPTIONS) {
      return 204;
    }

    location /api/auth/ {
      proxy_pass http://auth_service/auth/;

      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

    #   proxy_set_header Cookie $http_cookie;
    #   proxy_pass_header Set-Cookie;
    }

    location /api/users/ {
      proxy_pass http://user_service/users/;

      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/products/ {
      proxy_pass http://product_service/products/;

      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/inventory/ {
      proxy_pass http://inventory_service/inventory/;

      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/clients/ {
      proxy_pass http://client_service/clients/;

      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/assignments/ {
      proxy_pass http://assignment_service/assignments/;

      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/notifications/ {
      proxy_pass http://notification_service/notifications/;

      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/reports/ {
      proxy_pass http://report_service/reports/;

      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}